server:
  port: 8082

spring:
  application:
    name: chat-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:chatapp}
    password: ${RABBITMQ_DEFAULT_PASS:change-me}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    ch.m321.chatapp: INFO
